### ISSUE TITLE
ZeroToOne division implementation breaks invariant of [0, 1]

### ISSUE THREAD

**Issue by saona-raimundo** [khonsulabs/cushy#120]
Hi! Thanks for the crate! 

I come from [your last post](https://ecton.dev/introducing-gooey/) :)

I was checking your implementation of [ZeroToOne](https://github.com/khonsulabs/cushy/blob/15960da098b119a50c20f405c03ab1e8ae10aaab/src/animation.rs#L1114) and notice something.
You mentioned 

> `ZeroToOne` is a floating point number that is guaranteed to be between 0.0 and 1.0, inclusive.

But the [implementation of division](https://github.com/khonsulabs/cushy/blob/15960da098b119a50c20f405c03ab1e8ae10aaab/src/animation.rs#L1258) seems to break this.

There are various fixes: clamp after each division, check before dividing, etc. 
Notice that the implementation of `Div`, `DivAssign` and `Div<f32>` are affected.

I say it "seems to break" because I could not compile cushy 0.2 in Windows :/
(error[E0446]: crate-private type `InvalidationStatus` in public interface)
I have not tested this repo yet.

**Comment by ecton** [comment]
Good catch on the faulty div implementations.

> I say it "seems to break" because I could not compile cushy 0.2 in Windows :/
> (error[E0446]: crate-private type InvalidationStatus in public interface)

Well now that's really odd, as there's no window-specific code in the files that use that type. Can you provide me the full output including the command of what you're trying? What version of rust are you using?

**Comment by ddmgy** [comment]
> I say it "seems to break" because I could not compile cushy 0.2 in Windows :/
(error[E0446]: crate-private type InvalidationStatus in public interface)
I have not tested this repo yet.

I was facing the same error a few days ago. It was resolved by updating rustc to the latest stable version (from 1.73.0 to 1.75.0).

**Comment by ecton** [comment]
Thank you for letting me know @ddmgy. I've fixed the issue for the next release, and I've added a CI job to test the latest MSRV.

I believe all of the issues have been resolved. Please let me know if any other edge cases are found or build issues arise!

**Comment by saona-raimundo** [comment]
Thanks for looking into it! 

I confirm that updating Rust it compiles, sorry for that.

About the new implementation of division, it still fails :/ 
The division can lead to numbers larger than one that are not clamped.
Here is an example.
```rust
use cushy::animation::ZeroToOne;

fn main() {
	let a = ZeroToOne::new(1.0);
	let b: ZeroToOne = a / ZeroToOne::new(0.5);
	assert_eq!(b, 2.0);
}
```

The problem is in [this line](https://github.com/khonsulabs/cushy/blob/36d4239df565a892d17b0a341602daae47b591fa/src/animation.rs#L1156).
The checks done imply that the result will be positive, but not necessarily at most one.
It could be fixed clamping the result of the division.

**Comment by saona-raimundo** [comment]
If required, it seems simple to set up a verifier, for example [Prusti](https://viperproject.github.io/prusti-dev/user-guide/basic.html) or [Kani](https://model-checking.github.io/kani/tutorial-first-steps.html).
It seems like the perfect use-case :)

**Comment by ecton** [comment]
Definitely not required, I just need to not be so stupid. Not sure what I was thinking *either* of the last times I touched this code. Added test cases for negative rhs and `1.0 / < 1.0`.

I do love the idea of using Kani for some things however. It just really feels like overkill for this one type, and I'm not sure how much other stuff in Cushy itself is able to be fully formally verified. I think Figures would be amazing to have formal verification on, and I've thought of moving this ZeroToOne type to that crate because Kludgine could use it for opacity.
